// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace RestClientSDKLibrary.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// Model for the SelfMove extends GameBase
    /// </summary>
    public partial class SelfMove
    {
        /// <summary>
        /// Initializes a new instance of the SelfMove class.
        /// </summary>
        public SelfMove() { }

        /// <summary>
        /// Initializes a new instance of the SelfMove class.
        /// </summary>
        public SelfMove(IList<string> gameBoard, string playerSymbol)
        {
            GameBoard = gameBoard;
            PlayerSymbol = playerSymbol;
        }

        /// <summary>
        /// gameBoard string array
        /// </summary>
        [JsonProperty(PropertyName = "gameBoard")]
        public IList<string> GameBoard { get; set; }

        /// <summary>
        /// playerSymbol string
        /// </summary>
        [JsonProperty(PropertyName = "playerSymbol")]
        public string PlayerSymbol { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (GameBoard == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "GameBoard");
            }
            if (PlayerSymbol == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "PlayerSymbol");
            }
            if (this.GameBoard != null)
            {
                if (this.GameBoard.Count > 9)
                {
                    throw new ValidationException(ValidationRules.MaxItems, "GameBoard", 9);
                }
                if (this.GameBoard.Count < 9)
                {
                    throw new ValidationException(ValidationRules.MinItems, "GameBoard", 9);
                }
            }
            if (this.PlayerSymbol != null)
            {
                if (this.PlayerSymbol.Length > 1)
                {
                    throw new ValidationException(ValidationRules.MaxLength, "PlayerSymbol", 1);
                }
                if (this.PlayerSymbol.Length < 1)
                {
                    throw new ValidationException(ValidationRules.MinLength, "PlayerSymbol", 1);
                }
                if (!System.Text.RegularExpressions.Regex.IsMatch(this.PlayerSymbol, "^[O,X]{1}"))
                {
                    throw new ValidationException(ValidationRules.Pattern, "PlayerSymbol", "^[O,X]{1}");
                }
            }
        }
    }
}
